export const data = [
  {
    name: "ser",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "soy",
      tu: "eres",
      el: "es",
      nosotros: "somos",
      ellos: "son",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    imperfect: {
      yo: "era",
      tu: "eras",
      el: "era",
      nosotros: "éramos",
      ellos: "eran",
    },
  },
  {
    name: "estar",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "estoy",
      tu: "estás",
      el: "está",
      nosotros: "estamos",
      ellos: "están",
    },
    preterite: {
      yo: "estuve",
      tu: "estuviste",
      el: "estuvo",
      nosotros: "estuvimos",
      ellos: "estuvieron",
    },
    imperfect: {
      yo: "estaba",
      tu: "estabas",
      el: "estaba",
      nosotros: "estábamos",
      ellos: "estaban",
    },
  },
  {
    name: "tener",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "tengo",
      tu: "tienes",
      el: "tiene",
      nosotros: "tenemos",
      ellos: "tienen",
    },
    preterite: {
      yo: "tuve",
      tu: "tuviste",
      el: "tuvo",
      nosotros: "tuvimos",
      ellos: "tuvieron",
    },
    imperfect: {
      yo: "tenía",
      tu: "tenías",
      el: "tenía",
      nosotros: "teníamos",
      ellos: "tenían",
    },
  },
  {
    name: "hacer",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "hago",
      tu: "haces",
      el: "hace",
      nosotros: "hacemos",
      ellos: "hacen",
    },
    preterite: {
      yo: "hice",
      tu: "hiciste",
      el: "hizo",
      nosotros: "hicimos",
      ellos: "hicieron",
    },
    imperfect: {
      yo: "hacía",
      tu: "hacías",
      el: "hacía",
      nosotros: "hacíamos",
      ellos: "hacían",
    },
  },
  {
    name: "ir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "voy",
      tu: "vas",
      el: "va",
      nosotros: "vamos",
      ellos: "van",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    imperfect: {
      yo: "iba",
      tu: "ibas",
      el: "iba",
      nosotros: "íbamos",
      ellos: "iban",
    },
  },
  {
    name: "ver",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "veo",
      tu: "ves",
      el: "ve",
      nosotros: "vemos",
      ellos: "ven",
    },
    preterite: {
      yo: "vi",
      tu: "viste",
      el: "vio",
      nosotros: "vimos",
      ellos: "vieron",
    },
    imperfect: {
      yo: "veía",
      tu: "veías",
      el: "veía",
      nosotros: "veíamos",
      ellos: "veían",
    },
  },
  {
    name: "poder",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "puedo",
      tu: "puedes",
      el: "puede",
      nosotros: "podemos",
      ellos: "pueden",
    },
    preterite: {
      yo: "pude",
      tu: "pudiste",
      el: "pudo",
      nosotros: "pudimos",
      ellos: "pudieron",
    },
    imperfect: {
      yo: "podía",
      tu: "podías",
      el: "podía",
      nosotros: "podíamos",
      ellos: "podían",
    },
  },
  {
    name: "dar",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "doy",
      tu: "das",
      el: "da",
      nosotros: "damos",
      ellos: "dan",
    },
    preterite: {
      yo: "di",
      tu: "diste",
      el: "dio",
      nosotros: "dimos",
      ellos: "dieron",
    },
    imperfect: {
      yo: "daba",
      tu: "dabas",
      el: "daba",
      nosotros: "dábamos",
      ellos: "daban",
    },
  },
  {
    name: "saber",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "sé",
      tu: "sabes",
      el: "sabe",
      nosotros: "sabemos",
      ellos: "saben",
    },
    preterite: {
      yo: "supe",
      tu: "supiste",
      el: "supo",
      nosotros: "supimos",
      ellos: "supieron",
    },
    imperfect: {
      yo: "sabía",
      tu: "sabías",
      el: "sabía",
      nosotros: "sabíamos",
      ellos: "sabían",
    },
  },
  {
    name: "poner",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "pongo",
      tu: "pones",
      el: "pone",
      nosotros: "ponemos",
      ellos: "ponen",
    },
    preterite: {
      yo: "puse",
      tu: "pusiste",
      el: "puso",
      nosotros: "pusimos",
      ellos: "pusieron",
    },
    imperfect: {
      yo: "ponía",
      tu: "ponías",
      el: "ponía",
      nosotros: "poníamos",
      ellos: "ponían",
    },
  },
  {
    name: "pedir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "pido",
      tu: "pides",
      el: "pide",
      nosotros: "pedimos",
      ellos: "piden",
    },
    preterite: {
      yo: "pedí",
      tu: "pediste",
      el: "pidió",
      nosotros: "pedimos",
      ellos: "pidieron",
    },
    imperfect: {
      yo: "pedía",
      tu: "pedías",
      el: "pedía",
      nosotros: "pedíamos",
      ellos: "pedían",
    },
  },
  {
    name: "seguir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "sigo",
      tu: "sigues",
      el: "sigue",
      nosotros: "seguimos",
      ellos: "siguen",
    },
    preterite: {
      yo: "seguí",
      tu: "seguiste",
      el: "siguió",
      nosotros: "seguimos",
      ellos: "siguieron",
    },
    imperfect: {
      yo: "seguía",
      tu: "seguías",
      el: "seguía",
      nosotros: "seguíamos",
      ellos: "seguían",
    },
  },
  {
    name: "servir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "sirvo",
      tu: "sirves",
      el: "sirve",
      nosotros: "servimos",
      ellos: "sirven",
    },
    preterite: {
      yo: "serví",
      tu: "serviste",
      el: "sirvió",
      nosotros: "servimos",
      ellos: "sirvieron",
    },
    imperfect: {
      yo: "servía",
      tu: "servías",
      el: "servía",
      nosotros: "servíamos",
      ellos: "servían",
    },
  },
  {
    name: "elegir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "eligo",
      tu: "eliges",
      el: "elige",
      nosotros: "elegimos",
      ellos: "eligen",
    },
    preterite: {
      yo: "elegí",
      tu: "elegiste",
      el: "eligió",
      nosotros: "elegimos",
      ellos: "eligieron",
    },
    imperfect: {
      yo: "elegía",
      tu: "elegías",
      el: "elegía",
      nosotros: "elegíamos",
      ellos: "elegían",
    },
  },
  {
    name: "caer",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "caigo",
      tu: "caes",
      el: "cae",
      nosotros: "caemos",
      ellos: "caen",
    },
    preterite: {
      yo: "caí",
      tu: "caíste",
      el: "cayó",
      nosotros: "caímos",
      ellos: "cayeron",
    },
    imperfect: {
      yo: "caía",
      tu: "caías",
      el: "caía",
      nosotros: "caíamos",
      ellos: "caían",
    },
  },
  {
    name: "oír",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "oigo",
      tu: "oyes",
      el: "oye",
      nosotros: "oímos",
      ellos: "oyen",
    },
    preterite: {
      yo: "oí",
      tu: "oíste",
      el: "oyó",
      nosotros: "oímos",
      ellos: "oyeron",
    },
    imperfect: {
      yo: "oía",
      tu: "oías",
      el: "oía",
      nosotros: "oíamos",
      ellos: "oían",
    },
  },
  {
    name: "venir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "vengo",
      tu: "vienes",
      el: "viene",
      nosotros: "vemos",
      ellos: "vienen",
    },
    preterite: {
      yo: "vine",
      tu: "viniste",
      el: "vino",
      nosotros: "vinimos",
      ellos: "vinieron",
    },
    imperfect: {
      yo: "venía",
      tu: "venías",
      el: "venía",
      nosotros: "veníamos",
      ellos: "venían",
    },
  },
  {
    name: "traer",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "traigo",
      tu: "traes",
      el: "trae",
      nosotros: "traemos",
      ellos: "traen",
    },
    preterite: {
      yo: "traje",
      tu: "trajiste",
      el: "trajo",
      nosotros: "trajimos",
      ellos: "trajeron",
    },
    imperfect: {
      yo: "traía",
      tu: "traías",
      el: "traía",
      nosotros: "traíamos",
      ellos: "traían",
    },
  },
  {
    name: "haber",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "he",
      tu: "has",
      el: "ha",
      nosotros: "hemos",
      ellos: "han",
    },
    preterite: {
      yo: "hube",
      tu: "hubiste",
      el: "hubo",
      nosotros: "hubimos",
      ellos: "hubieron",
    },
    imperfect: {
      yo: "había",
      tu: "habías",
      el: "había",
      nosotros: "habíamos",
      ellos: "habían",
    },
  },
  {
    name: "salir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "salgo",
      tu: "sales",
      el: "sale",
      nosotros: "salimos",
      ellos: "salen",
    },
    preterite: {
      yo: "salí",
      tu: "saliste",
      el: "salió",
      nosotros: "salimos",
      ellos: "salieron",
    },
    imperfect: {
      yo: "salía",
      tu: "salías",
      el: "salía",
      nosotros: "salíamos",
      ellos: "salían",
    },
  },
];
