export const data = [
  {
    option: "centrábamos",
    answer: "to focus",
  },
  {
    option: "ganas",
    answer: "desire",
  },
  {
    option: "parecía",
    answer: "to seem",
  },
  {
    option: "avanzar",
    answer: "to advance",
  },
  {
    option: "exigir",
    answer: "to require",
  },
  {
    option: 'dirigir',
    answer: 'to lead',
  }
];

export const verbs = [
  {
    name: "ser",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "soy",
      tu: "eres",
      el: "es",
      nosotros: "somos",
      ellos: "son",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    imperfect: {
      yo: "era",
      tu: "eras",
      el: "era",
      nosotros: "éramos",
      ellos: "eran",
    },
  },
  {
    name: "estar",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "estoy",
      tu: "estás",
      el: "está",
      nosotros: "estamos",
      ellos: "están",
    },
    preterite: {
      yo: "estuve",
      tu: "estuviste",
      el: "estuvo",
      nosotros: "estuvimos",
      ellos: "estuvieron",
    },
    imperfect: {
      yo: "estaba",
      tu: "estabas",
      el: "estaba",
      nosotros: "estábamos",
      ellos: "estaban",
    },
  },
  {
    name: "tener",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "tengo",
      tu: "tienes",
      el: "tiene",
      nosotros: "tenemos",
      ellos: "tienen",
    },
    preterite: {
      yo: "tuve",
      tu: "tuviste",
      el: "tuvo",
      nosotros: "tuvimos",
      ellos: "tuvieron",
    },
    imperfect: {
      yo: "tenía",
      tu: "tenías",
      el: "tenía",
      nosotros: "teníamos",
      ellos: "tenían",
    },
  },
  {
    name: "hacer",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "hago",
      tu: "haces",
      el: "hace",
      nosotros: "hacemos",
      ellos: "hacen",
    },
    preterite: {
      yo: "hice",
      tu: "hiciste",
      el: "hizo",
      nosotros: "hicimos",
      ellos: "hicieron",
    },
    imperfect: {
      yo: "hacía",
      tu: "hacías",
      el: "hacía",
      nosotros: "hacíamos",
      ellos: "hacían",
    },
  },
  {
    name: "ir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "voy",
      tu: "vas",
      el: "va",
      nosotros: "vamos",
      ellos: "van",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    imperfect: {
      yo: "iba",
      tu: "ibas",
      el: "iba",
      nosotros: "íbamos",
      ellos: "iban",
    },
  },
  {
    name: "ver",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "veo",
      tu: "ves",
      el: "ve",
      nosotros: "vemos",
      ellos: "ven",
    },
    preterite: {
      yo: "vi",
      tu: "viste",
      el: "vio",
      nosotros: "vimos",
      ellos: "vieron",
    },
    imperfect: {
      yo: "veía",
      tu: "veías",
      el: "veía",
      nosotros: "veíamos",
      ellos: "veían",
    },
  },
  {
    name: "poder",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "puedo",
      tu: "puedes",
      el: "puede",
      nosotros: "podemos",
      ellos: "pueden",
    },
    preterite: {
      yo: "pude",
      tu: "pudiste",
      el: "pudo",
      nosotros: "pudimos",
      ellos: "pudieron",
    },
    imperfect: {
      yo: "podía",
      tu: "podías",
      el: "podía",
      nosotros: "podíamos",
      ellos: "podían",
    },
  },
  {
    name: "dar",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "doy",
      tu: "das",
      el: "da",
      nosotros: "damos",
      ellos: "dan",
    },
    preterite: {
      yo: "di",
      tu: "diste",
      el: "dio",
      nosotros: "dimos",
      ellos: "dieron",
    },
    imperfect: {
      yo: "daba",
      tu: "dabas",
      el: "daba",
      nosotros: "dábamos",
      ellos: "daban",
    },
  },
  {
    name: "saber",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "sé",
      tu: "sabes",
      el: "sabe",
      nosotros: "sabemos",
      ellos: "saben",
    },
    preterite: {
      yo: "supe",
      tu: "supiste",
      el: "supo",
      nosotros: "supimos",
      ellos: "supieron",
    },
    imperfect: {
      yo: "sabía",
      tu: "sabías",
      el: "sabía",
      nosotros: "sabíamos",
      ellos: "sabían",
    },
  },
  {
    name: "poner",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "pongo",
      tu: "pones",
      el: "pone",
      nosotros: "ponemos",
      ellos: "ponen",
    },
    preterite: {
      yo: "puse",
      tu: "pusiste",
      el: "puso",
      nosotros: "pusimos",
      ellos: "pusieron",
    },
    imperfect: {
      yo: "ponía",
      tu: "ponías",
      el: "ponía",
      nosotros: "poníamos",
      ellos: "ponían",
    },
  },
  {
    name: "pedir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "pido",
      tu: "pides",
      el: "pide",
      nosotros: "pedimos",
      ellos: "piden",
    },
    preterite: {
      yo: "pedí",
      tu: "pediste",
      el: "pidió",
      nosotros: "pedimos",
      ellos: "pidieron",
    },
    imperfect: {
      yo: "pedía",
      tu: "pedías",
      el: "pedía",
      nosotros: "pedíamos",
      ellos: "pedían",
    },
  },
  {
    name: "seguir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "sigo",
      tu: "sigues",
      el: "sigue",
      nosotros: "seguimos",
      ellos: "siguen",
    },
    preterite: {
      yo: "seguí",
      tu: "seguiste",
      el: "siguió",
      nosotros: "seguimos",
      ellos: "siguieron",
    },
    imperfect: {
      yo: "seguía",
      tu: "seguías",
      el: "seguía",
      nosotros: "seguíamos",
      ellos: "seguían",
    },
  },
  {
    name: "servir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "sirvo",
      tu: "sirves",
      el: "sirve",
      nosotros: "servimos",
      ellos: "sirven",
    },
    preterite: {
      yo: "serví",
      tu: "serviste",
      el: "sirvió",
      nosotros: "servimos",
      ellos: "sirvieron",
    },
    imperfect: {
      yo: "servía",
      tu: "servías",
      el: "servía",
      nosotros: "servíamos",
      ellos: "servían",
    },
  },
  {
    name: "elegir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "eligo",
      tu: "eliges",
      el: "elige",
      nosotros: "elegimos",
      ellos: "eligen",
    },
    preterite: {
      yo: "elegí",
      tu: "elegiste",
      el: "eligió",
      nosotros: "elegimos",
      ellos: "eligieron",
    },
    imperfect: {
      yo: "elegía",
      tu: "elegías",
      el: "elegía",
      nosotros: "elegíamos",
      ellos: "elegían",
    },
  },
  {
    name: "caer",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "caigo",
      tu: "caes",
      el: "cae",
      nosotros: "caemos",
      ellos: "caen",
    },
    preterite: {
      yo: "caí",
      tu: "caíste",
      el: "cayó",
      nosotros: "caímos",
      ellos: "cayeron",
    },
    imperfect: {
      yo: "caía",
      tu: "caías",
      el: "caía",
      nosotros: "caíamos",
      ellos: "caían",
    },
  },
  {
    name: "oír",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "oigo",
      tu: "oyes",
      el: "oye",
      nosotros: "oímos",
      ellos: "oyen",
    },
    preterite: {
      yo: "oí",
      tu: "oíste",
      el: "oyó",
      nosotros: "oímos",
      ellos: "oyeron",
    },
    imperfect: {
      yo: "oía",
      tu: "oías",
      el: "oía",
      nosotros: "oíamos",
      ellos: "oían",
    },
  },
  {
    name: "venir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "vengo",
      tu: "vienes",
      el: "viene",
      nosotros: "venimos",
      ellos: "vienen",
    },
    preterite: {
      yo: "vine",
      tu: "viniste",
      el: "vino",
      nosotros: "vinimos",
      ellos: "vinieron",
    },
    imperfect: {
      yo: "venía",
      tu: "venías",
      el: "venía",
      nosotros: "veníamos",
      ellos: "venían",
    },
  },
  {
    name: "traer",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "traigo",
      tu: "traes",
      el: "trae",
      nosotros: "traemos",
      ellos: "traen",
    },
    preterite: {
      yo: "traje",
      tu: "trajiste",
      el: "trajo",
      nosotros: "trajimos",
      ellos: "trajeron",
    },
    imperfect: {
      yo: "traía",
      tu: "traías",
      el: "traía",
      nosotros: "traíamos",
      ellos: "traían",
    },
  },
  {
    name: "haber",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "he",
      tu: "has",
      el: "ha",
      nosotros: "hemos",
      ellos: "han",
    },
    preterite: {
      yo: "",
      tu: "",
      el: "",
      nosotros: "",
      ellos: "",
    },
    imperfect: {
      yo: "había",
      tu: "habías",
      el: "había",
      nosotros: "habíamos",
      ellos: "habían",
    },
  },
  {
    name: "salir",
    pastParticiple: "",
    gerund: "",
    present: {
      yo: "salgo",
      tu: "sales",
      el: "sale",
      nosotros: "salimos",
      ellos: "salen",
    },
    preterite: {
      yo: "salí",
      tu: "saliste",
      el: "salió",
      nosotros: "salimos",
      ellos: "salieron",
    },
    imperfect: {
      yo: "salía",
      tu: "salías",
      el: "salía",
      nosotros: "salíamos",
      ellos: "salían",
    },
  },
];

export const otherVerbs = [
  {
    name: "hablar",
    pastParticiple: "hablado",
    gerund: "hablando",
    present: {
      yo: "hablo",
      tu: "hablas",
      el: "habla",
      nosotros: "hablamos",
      ellos: "hablan",
    },
    preterite: {
      yo: "hablé",
      tu: "hablaste",
      el: "habló",
      nosotros: "hablamos",
      ellos: "hablaron",
    },
    imperfect: {
      yo: "hablaba",
      tu: "hablabas",
      el: "hablaba",
      nosotros: "hablabamos",
      ellos: "hablaban",
    },
  },
  {
    name: "mirar",
    pastParticiple: "mirado",
    gerund: "mirando",
    present: {
      yo: "miro",
      tu: "miras",
      el: "mira",
      nosotros: "miramos",
      ellos: "miran",
    },
    preterite: {
      yo: "miré",
      tu: "miraste",
      el: "miró",
      nosotros: "miramos",
      ellos: "miraron",
    },
    imperfect: {
      yo: "miraba",
      tu: "mirabas",
      el: "miraba",
      nosotros: "mirabamos",
      ellos: "miraban",
    },
  },
  {
    name: "escuchar",
    pastParticiple: "escuchado",
    gerund: "escuchando",
    present: {
      yo: "escucho",
      tu: "escuchas",
      el: "escucha",
      nosotros: "escuchamos",
      ellos: "escuchan",
    },
    preterite: {
      yo: "escuché",
      tu: "escuchaste",
      el: "escuchó",
      nosotros: "escuchamos",
      ellos: "escucharon",
    },
    imperfect: {
      yo: "escuchaba",
      tu: "escuchabas",
      el: "escuchaba",
      nosotros: "escuchabamos",
      ellos: "escuchaban",
    },
  },
  {
    name: "ayudar",
    pastParticiple: "ayudado",
    gerund: "ayudando",
    present: {
      yo: "ayudo",
      tu: "ayudas",
      el: "ayuda",
      nosotros: "ayudamos",
      ellos: "ayudan",
    },
    preterite: {
      yo: "ayudé",
      tu: "ayudaste",
      el: "ayudó",
      nosotros: "ayudamos",
      ellos: "ayudaron",
    },
    imperfect: {
      yo: "ayudaba",
      tu: "ayudabas",
      el: "ayudaba",
      nosotros: "ayudabamos",
      ellos: "ayudaban",
    },
  },
  {
    name: "tomar",
    pastParticiple: "tomado",
    gerund: "tomando",
    present: {
      yo: "tomo",
      tu: "tomas",
      el: "toma",
      nosotros: "tomamos",
      ellos: "toman",
    },
    preterite: {
      yo: "tomé",
      tu: "tomaste",
      el: "tomó",
      nosotros: "tomamos",
      ellos: "tomaron",
    },
    imperfect: {
      yo: "tomaba",
      tu: "tomabas",
      el: "tomaba",
      nosotros: "tomabamos",
      ellos: "tomaban",
    },
  },
  {
    name: "comer",
    pastParticiple: "comido",
    gerund: "comiendo",
    present: {
      yo: "como",
      tu: "comes",
      el: "come",
      nosotros: "comemos",
      ellos: "comen",
    },
    preterite: {
      yo: "comí",
      tu: "comiste",
      el: "comió",
      nosotros: "comimos",
      ellos: "comieron",
    },
    imperfect: {
      yo: "comía",
      tu: "comías",
      el: "comía",
      nosotros: "comíamos",
      ellos: "comían",
    },
  },
  {
    name: "aprender",
    pastParticiple: "aprendido",
    gerund: "aprendiendo",
    present: {
      yo: "aprendo",
      tu: "aprendes",
      el: "aprende",
      nosotros: "aprendemos",
      ellos: "aprenden",
    },
    preterite: {
      yo: "aprendí",
      tu: "aprendiste",
      el: "aprendió",
      nosotros: "aprendimos",
      ellos: "aprendieron",
    },
    imperfect: {
      yo: "aprendía",
      tu: "aprendías",
      el: "aprendía",
      nosotros: "aprendíamos",
      ellos: "aprendían",
    },
  },
  {
    name: "deber",
    pastParticiple: "debido",
    gerund: "debiendo",
    present: {
      yo: "debo",
      tu: "debes",
      el: "debe",
      nosotros: "debemos",
      ellos: "deben",
    },
    preterite: {
      yo: "debí",
      tu: "debiste",
      el: "debió",
      nosotros: "debimos",
      ellos: "debieron",
    },
    imperfect: {
      yo: "debía",
      tu: "debías",
      el: "debía",
      nosotros: "debíamos",
      ellos: "debían",
    },
  },
  {
    name: "leer",
    pastParticiple: "leido",
    gerund: "leyndo",
    present: {
      yo: "leo",
      tu: "lees",
      el: "lee",
      nosotros: "leemos",
      ellos: "leen",
    },
    preterite: {
      yo: "leí",
      tu: "leíste",
      el: "leyó",
      nosotros: "leímos",
      ellos: "leyeron",
    },
    imperfect: {
      yo: "leía",
      tu: "leías",
      el: "leía",
      nosotros: "leíamos",
      ellos: "leían",
    },
  },
  {
    name: "vivir",
    pastParticiple: "vivido",
    gerund: "viviendo",
    present: {
      yo: "vivo",
      tu: "vives",
      el: "vive",
      nosotros: "vivimos",
      ellos: "viven",
    },
    preterite: {
      yo: "viví",
      tu: "viviste",
      el: "vivió",
      nosotros: "vivimos",
      ellos: "vivieron",
    },
    imperfect: {
      yo: "vivía",
      tu: "vivías",
      el: "vivía",
      nosotros: "vivíamos",
      ellos: "vivían",
    },
  },
  {
    name: "permitir",
    pastParticiple: "permitido",
    gerund: "permitiendo",
    present: {
      yo: "permito",
      tu: "permites",
      el: "permite",
      nosotros: "permitimos",
      ellos: "permiten",
    },
    preterite: {
      yo: "permití",
      tu: "permitiste",
      el: "permitió",
      nosotros: "permitimos",
      ellos: "permitieron",
    },
    imperfect: {
      yo: "permitía",
      tu: "permitías",
      el: "permitía",
      nosotros: "permitíamos",
      ellos: "permitían",
    },
  },
  {
    name: "recibir",
    pastParticiple: "recibido",
    gerund: "recibiendo",
    present: {
      yo: "recibo",
      tu: "recibes",
      el: "recibe",
      nosotros: "recibimos",
      ellos: "reciben",
    },
    preterite: {
      yo: "recibí",
      tu: "recibiste",
      el: "recibió",
      nosotros: "recibimos",
      ellos: "recibieron",
    },
    imperfect: {
      yo: "recibía",
      tu: "recibías",
      el: "recibía",
      nosotros: "recibíamos",
      ellos: "recibían",
    },
  },
  {
    name: "abrir",
    pastParticiple: "abierto",
    gerund: "abriendo",
    present: {
      yo: "abro",
      tu: "abres",
      el: "abre",
      nosotros: "abrimos",
      ellos: "abren",
    },
    preterite: {
      yo: "abrí",
      tu: "abriste",
      el: "abrió",
      nosotros: "abrimos",
      ellos: "abrieron",
    },
    imperfect: {
      yo: "abría",
      tu: "abrías",
      el: "abría",
      nosotros: "abríamos",
      ellos: "abrían",
    },
  },
  {
    name: "alcanzar",
    pastParticiple: "alcanzado",
    gerund: "alcanzando",
    present: {
      yo: "alcanzo",
      tu: "alcanzas",
      el: "alcanza",
      nosotros: "alcanzamos",
      ellos: "alcanzan",
    },
    preterite: {
      yo: "alcancé",
      tu: "alcanzaste",
      el: "alcanzó",
      nosotros: "alcanzamos",
      ellos: "alcanzaron",
    },
    imperfect: {
      yo: "alcanzaba",
      tu: "alcanzabas",
      el: "alcanzaba",
      nosotros: "alcanzabamos",
      ellos: "alcanzaban",
    },
  },
  {
    name: "llegar",
    pastParticiple: "llegado",
    gerund: "llegando",
    present: {
      yo: "llego",
      tu: "llegas",
      el: "llega",
      nosotros: "llegamos",
      ellos: "llegan",
    },
    preterite: {
      yo: "llegué",
      tu: "llegaste",
      el: "llegó",
      nosotros: "llegamos",
      ellos: "llegaron",
    },
    imperfect: {
      yo: "llegaba",
      tu: "llegabas",
      el: "llegaba",
      nosotros: "llegabamos",
      ellos: "llegaban",
    },
  },
  {
    name: "buscar",
    pastParticiple: "buscado",
    gerund: "buscando",
    present: {
      yo: "busco",
      tu: "buscas",
      el: "busca",
      nosotros: "buscamos",
      ellos: "buscan",
    },
    preterite: {
      yo: "busqué",
      tu: "buscaste",
      el: "buscó",
      nosotros: "buscamos",
      ellos: "buscaron",
    },
    imperfect: {
      yo: "buscaba",
      tu: "buscabas",
      el: "buscaba",
      nosotros: "buscabamos",
      ellos: "buscaban",
    },
  },
  {
    name: "parecer",
    pastParticiple: "parecido",
    gerund: "pareciendo",
    present: {
      yo: "parezco",
      tu: "pareces",
      el: "parece",
      nosotros: "parecemos",
      ellos: "parecen",
    },
    preterite: {
      yo: "parecí",
      tu: "pareciste",
      el: "pareció",
      nosotros: "parecimos",
      ellos: "parecieron",
    },
    imperfect: {
      yo: "parecía",
      tu: "parecías",
      el: "parecía",
      nosotros: "parecíamos",
      ellos: "parecían",
    },
  },
  {
    name: "conocer",
    pastParticiple: "conocido",
    gerund: "conociendo",
    present: {
      yo: "conozco",
      tu: "conoces",
      el: "conoce",
      nosotros: "conocimos",
      ellos: "conocen",
    },
    preterite: {
      yo: "conocí",
      tu: "conociste",
      el: "conoció",
      nosotros: "conocimos",
      ellos: "conocieron",
    },
    imperfect: {
      yo: "conocía",
      tu: "conocías",
      el: "conocía",
      nosotros: "conocíamos",
      ellos: "conocían",
    },
  },
  {
    name: "querer",
    pastParticiple: "querido",
    gerund: "queriendo",
    present: {
      yo: "quiero",
      tu: "quieres",
      el: "quiere",
      nosotros: "querimos",
      ellos: "quieren",
    },
    preterite: {
      yo: "quise",
      tu: "quesiste",
      el: "quiso",
      nosotros: "quirimos",
      ellos: "quisieron",
    },
    imperfect: {
      yo: "quería",
      tu: "querías",
      el: "quería",
      nosotros: "queríamos",
      ellos: "querían",
    },
  },
  {
    name: "dirigir",
    pastParticiple: "dirigido",
    gerund: "dirigiendo",
    present: {
      yo: "dirijo",
      tu: "diriges",
      el: "dirige",
      nosotros: "dirigimos",
      ellos: "dirigen",
    },
    preterite: {
      yo: "dirigí",
      tu: "dirigiste",
      el: "dirigió",
      nosotros: "dirigimos",
      ellos: "dirigieron",
    },
    imperfect: {
      yo: "dirigía",
      tu: "dirigías",
      el: "dirigía",
      nosotros: "dirigíamos",
      ellos: "dirigían",
    },
  },
  {
    name: "construir",
    pastParticiple: "construido",
    gerund: "construyendo",
    present: {
      yo: "construyo",
      tu: "construyes",
      el: "construye",
      nosotros: "construimos",
      ellos: "construyen",
    },
    preterite: {
      yo: "construí",
      tu: "construiste",
      el: "construyó",
      nosotros: "construimos",
      ellos: "construyeron",
    },
    imperfect: {
      yo: "construía",
      tu: "construías",
      el: "construía",
      nosotros: "construíamos",
      ellos: "construían",
    },
  },
  {
    name: "exigir",
    pastParticiple: "exigido",
    gerund: "exigiendo",
    present: {
      yo: "exijo",
      tu: "exiges",
      el: "exige",
      nosotros: "exigimos",
      ellos: "exigen",
    },
    preterite: {
      yo: "exigí",
      tu: "exigiste",
      el: "exigió",
      nosotros: "exigimos",
      ellos: "exigieron",
    },
    imperfect: {
      yo: "exigía",
      tu: "exigías",
      el: "exigía",
      nosotros: "exigíamos",
      ellos: "exigían",
    },
  },
  {
    name: "decir",
    pastParticiple: "dicho",
    gerund: "diciendo",
    present: {
      yo: "digo",
      tu: "dices",
      el: "dice",
      nosotros: "decimos",
      ellos: "dicen",
    },
    preterite: {
      yo: "dije",
      tu: "dijiste",
      el: "dijo",
      nosotros: "dijimos",
      ellos: "dijeron",
    },
    imperfect: {
      yo: "decía",
      tu: "decías",
      el: "decía",
      nosotros: "decíamos",
      ellos: "decían",
    },
  },
  {
    name: "jugar",
    pastParticiple: "jugado",
    gerund: "jugando",
    present: {
      yo: "juego",
      tu: "juegas",
      el: "juega",
      nosotros: "jugamos",
      ellos: "juegan",
    },
    preterite: {
      yo: "jugué",
      tu: "jugaste",
      el: "jugó",
      nosotros: "jugamos",
      ellos: "jugaron",
    },
    imperfect: {
      yo: "jugaba",
      tu: "jugabas",
      el: "jugaba",
      nosotros: "jugabamos",
      ellos: "jugaban",
    },
  },
  {
    name: "pensar",
    pastParticiple: "pensado",
    gerund: "pensando",
    present: {
      yo: "pienso",
      tu: "piensas",
      el: "piensa",
      nosotros: "pensamos",
      ellos: "piensan",
    },
    preterite: {
      yo: "pensé",
      tu: "pensaste",
      el: "pensó",
      nosotros: "pensamos",
      ellos: "pensaron",
    },
    imperfect: {
      yo: "pensaba",
      tu: "pensabas",
      el: "pensaba",
      nosotros: "pensabamos",
      ellos: "pensaban",
    },
  },
  {
    name: "empezar",
    pastParticiple: "empezado",
    gerund: "empezando",
    present: {
      yo: "empiezo",
      tu: "empiezas",
      el: "empieza",
      nosotros: "empezamos",
      ellos: "empiezan",
    },
    preterite: {
      yo: "empecé",
      tu: "empezaste",
      el: "empezó",
      nosotros: "empezamos",
      ellos: "empezaron",
    },
    imperfect: {
      yo: "empezaba",
      tu: "empezabas",
      el: "empezaba",
      nosotros: "empezabamos",
      ellos: "empezaban",
    },
  },
  {
    name: "entender",
    pastParticiple: "entendido",
    gerund: "entendiendo",
    present: {
      yo: "entiendo",
      tu: "entiendes",
      el: "entiende",
      nosotros: "entendemos",
      ellos: "entienden",
    },
    preterite: {
      yo: "entendí",
      tu: "entendiste",
      el: "entendió",
      nosotros: "entendimos",
      ellos: "entendieron",
    },
    imperfect: {
      yo: "entendía",
      tu: "entendías",
      el: "entendía",
      nosotros: "entendíamos",
      ellos: "entendían",
    },
  },
  {
    name: "volver",
    pastParticiple: "vuelto",
    gerund: "volviendo",
    present: {
      yo: "vuelvo",
      tu: "vuelves",
      el: "vuelve",
      nosotros: "volvemos",
      ellos: "vuelven",
    },
    preterite: {
      yo: "volví",
      tu: "volviste",
      el: "volvió",
      nosotros: "volvimos",
      ellos: "volvieron",
    },
    imperfect: {
      yo: "volvía",
      tu: "volvías",
      el: "volvía",
      nosotros: "volvíamos",
      ellos: "volvían",
    },
  },
  {
    name: "doler",
    pastParticiple: "dolido",
    gerund: "doliendo",
    present: {
      yo: "duelo",
      tu: "dueles",
      el: "duele",
      nosotros: "dolemos",
      ellos: "duelen",
    },
    preterite: {
      yo: "dolí",
      tu: "doliste",
      el: "dolió",
      nosotros: "dolimos",
      ellos: "dolieron",
    },
    imperfect: {
      yo: "dolía",
      tu: "dolías",
      el: "dolía",
      nosotros: "dolíamos",
      ellos: "dolían",
    },
  },
  {
    name: "sentir",
    pastParticiple: "sentido",
    gerund: "sentiendo",
    present: {
      yo: "siento",
      tu: "sientes",
      el: "siente",
      nosotros: "sentimos",
      ellos: "sienten",
    },
    preterite: {
      yo: "sentí",
      tu: "sentiste",
      el: "sintió",
      nosotros: "sentimos",
      ellos: "sintieron",
    },
    imperfect: {
      yo: "sentía",
      tu: "sentías",
      el: "sentía",
      nosotros: "sentíamos",
      ellos: "sentían",
    },
  },
  {
    name: "morir",
    pastParticiple: "muerto",
    gerund: "muriendo",
    present: {
      yo: "muero",
      tu: "mueres",
      el: "muere",
      nosotros: "morimos",
      ellos: "mueren",
    },
    preterite: {
      yo: "morí",
      tu: "moriste",
      el: "murió",
      nosotros: "morimos",
      ellos: "murieron",
    },
    imperfect: {
      yo: "moría",
      tu: "morías",
      el: "moría",
      nosotros: "moríamos",
      ellos: "morían",
    },
  },
  {
    name: "conseguir",
    pastParticiple: "conseguido",
    gerund: "consiguiendo",
    present: {
      yo: "consigo",
      tu: "consigues",
      el: "consigue",
      nosotros: "conseguimos",
      ellos: "consiguen",
    },
    preterite: {
      yo: "conseguí",
      tu: "conseguiste",
      el: "conseguió",
      nosotros: "conseguimos",
      ellos: "conseguieron",
    },
    imperfect: {
      yo: "conseguía",
      tu: "conseguías",
      el: "conseguía",
      nosotros: "conseguíamos",
      ellos: "conseguían",
    },
  },
];
